#!/bin/sh

# intercept `ifconfig socat0 up`
[ "socat0" == "$1" ] && exit 0

# todo generate this dynamically ???
export PATH="/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin:/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets"

exec ifconfig "$@"